stages:
  - build
  - release

variables:
  REPO_NAME: spark-heimdall

# Template for Go builds
.go-build:
  image: golang:1.24
  stage: build
  script:
    - mkdir -p dist
    - GO111MODULE=on CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o dist/$REPO_NAME-$GOOS-$GOARCH -ldflags "-s -w -X main.version=$CI_COMMIT_TAG" ./main.go
  artifacts:
    paths:
      - dist/

# Build for various platforms
build:linux-amd64:
  extends: .go-build
  variables:
    GOOS: linux
    GOARCH: amd64

build:linux-arm64:
  extends: .go-build
  variables:
    GOOS: linux
    GOARCH: arm64

build:darwin-amd64:
  extends: .go-build
  variables:
    GOOS: darwin
    GOARCH: amd64

build:darwin-arm64:
  extends: .go-build
  variables:
    GOOS: darwin
    GOARCH: arm64

build:windows-amd64:
  extends: .go-build
  variables:
    GOOS: windows
    GOARCH: amd64
  script:
    - mkdir -p dist
    - GO111MODULE=on CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o dist/$REPO_NAME-$GOOS-$GOARCH.exe -ldflags "-s -w" ./main.go

# Create a release when a tag is pushed
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build:linux-amd64
    - build:linux-arm64
    - build:darwin-amd64
    - build:darwin-arm64
    - build:windows-amd64
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Linux (x86_64)'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/raw/dist/${REPO_NAME}-linux-amd64?job=build:linux-amd64'
        - name: 'Linux (ARM64)'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/raw/dist/${REPO_NAME}-linux-arm64?job=build:linux-arm64'
        - name: 'macOS (x86_64)'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/raw/dist/${REPO_NAME}-darwin-amd64?job=build:darwin-amd64'
        - name: 'macOS (ARM64/M1)'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/raw/dist/${REPO_NAME}-darwin-arm64?job=build:darwin-arm64'
        - name: 'Windows (x86_64)'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/raw/dist/${REPO_NAME}-windows-amd64.exe?job=build:windows-amd64'